### ISSUE TITLE
For PID:01 23 name: "FuelRailPressureCommand.class" there is Exceptions trouble

### ISSUE THREAD

**Issue by Kolyall** [pires/android-obd-reader#166]
For command: PID:`01 23` name: "`FuelRailPressureCommand.class`" 
`W/System.err: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3`
`W/System.err:at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)`
`W/System.err:     at java.util.ArrayList.get(ArrayList.java:308)`
`W/System.err:     at com.github.pires.obd.commands.fuel.ConsumptionRateCommand.performCalculations(ConsumptionRateCommand.java:36)`
`W/System.err:     at com.github.pires.obd.commands.ObdCommand.readResult(ObdCommand.java:125)`
`W/System.err:     at com.github.pires.obd.commands.ObdCommand.run(ObdCommand.java:77)`
`W/System.err:     at com.github.pires.obd.reader.io.ObdGatewayService.executeQueue(ObdGatewayService.java:199)`
`W/System.err:     at com.github.pires.obd.reader.io.AbstractGatewayService$1.run(AbstractGatewayService.java:39)`

**Comment by Kolyall** [comment]
Duplicate of https://github.com/pires/android-obd-reader/issues/164
