### ISSUE TITLE
Will crash if "Start Live Data" with no bluetooth device connected

### ISSUE THREAD

**Issue by ss1271** [pires/android-obd-reader#26]
How to reproduce:
* Turn on Bluetooth and don't connect to any bluetooth devices
* Open the app, and tap "Start Live Data"

Device:
Nexus 4 with stock 4.4.4 (KTU84P), no root access

Here's the log:

    07-08 11:43:14.307  17491-17491/pt.lighthouselabs.obd.reader E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: pt.lighthouselabs.obd.reader, PID: 17491
    java.lang.IllegalArgumentException: null is not a valid Bluetooth address
            at android.bluetooth.BluetoothDevice.<init>(BluetoothDevice.java:564)
            at android.bluetooth.BluetoothAdapter.getRemoteDevice(BluetoothAdapter.java:458)
            at pt.lighthouselabs.obd.reader.io.ObdGatewayService.startService(ObdGatewayService.java:117)
            at pt.lighthouselabs.obd.reader.activity.MainActivity.startLiveData(MainActivity.java:283)
            at pt.lighthouselabs.obd.reader.activity.MainActivity.onOptionsItemSelected(MainActivity.java:256)
            at android.app.Activity.onMenuItemSelected(Activity.java:2600)
            at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1012)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
            at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:177)
            at android.widget.AdapterView.performItemClick(AdapterView.java:299)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
            at android.widget.AbsListView$3.run(AbsListView.java:3645)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)

**Comment by nomwerp** [comment]
i've just created a pull request that should fix this  , still needs to be tested (but should be safe) for the case there is a bluetooth adapter selected since my phone doesn't have a working one at the moment ;)
